name: app_movil_iptv
description: App Movil IPTV - Channels, Movies and Series.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-117.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  flutter_staggered_grid_view: ^0.6.2
  flutter_secure_storage: ^8.0.0
  #flutter_vlc_player: ^7.2.0
  carousel_slider: ^4.2.1
  transparent_image: ^2.0.1
  webview_flutter: ^4.0.5
  tmdb_api: ^2.1.5
  lottie: ^2.4.0
  intl: ^0.18.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/animation/
